//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace net { namespace protosystem { namespace GarageDoor {

ref class GarageDoorSignals;

public interface class IGarageDoorSignals
{
    event Windows::Foundation::TypedEventHandler<GarageDoorSignals^, GarageDoorGarageDoorStateChangedReceivedEventArgs^>^ GarageDoorStateChangedReceived;
};

public ref class GarageDoorSignals sealed : [Windows::Foundation::Metadata::Default] IGarageDoorSignals
{
public:
    // Calling this method will send the GarageDoorStateChanged signal to every member of the session.
    void GarageDoorStateChanged(_In_ uint32 interfaceMemberOldState, _In_ uint32 interfaceMemberNewState, _In_ int64 interfaceMemberElapsedTime);

    // This event fires whenever the GarageDoorStateChanged signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<GarageDoorSignals^, GarageDoorGarageDoorStateChangedReceivedEventArgs^>^ GarageDoorStateChangedReceived;

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallGarageDoorStateChangedReceived(_In_ GarageDoorSignals^ sender, _In_ GarageDoorGarageDoorStateChangedReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    alljoyn_interfacedescription_member m_memberGarageDoorStateChanged;
};

} } } 
