//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace net { namespace protosystem { namespace GarageDoor {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IGarageDoorService. Instead, GarageDoorServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class GarageDoorServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IGarageDoorService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorOpenOrCloseGarageCalledEventArgs^>^ OpenOrCloseGarageCalled;
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorOpenGarageCalledEventArgs^>^ OpenGarageCalled;
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorCloseGarageCalledEventArgs^>^ CloseGarageCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorGetVersionRequestedEventArgs^>^ GetVersionRequested;
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorGetServiceVersionRequestedEventArgs^>^ GetServiceVersionRequested;
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorGetLocationRequestedEventArgs^>^ GetLocationRequested;
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorGetDoorStateRequestedEventArgs^>^ GetDoorStateRequested;
    
    // Property Write Events
    event Windows::Foundation::TypedEventHandler<GarageDoorServiceEventAdapter^, GarageDoorSetLocationRequestedEventArgs^>^ SetLocationRequested;

    // IGarageDoorService Implementation
    virtual Windows::Foundation::IAsyncOperation<GarageDoorOpenOrCloseGarageResult^>^ OpenOrCloseGarageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ bool interfaceMemberOpen);
    virtual Windows::Foundation::IAsyncOperation<GarageDoorOpenGarageResult^>^ OpenGarageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<GarageDoorCloseGarageResult^>^ CloseGarageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<GarageDoorGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<GarageDoorGetServiceVersionResult^>^ GetServiceVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<GarageDoorGetLocationResult^>^ GetLocationAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<GarageDoorGetDoorStateResult^>^ GetDoorStateAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<GarageDoorSetLocationResult^>^ SetLocationAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ value);
};

} } } 
