//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace net::protosystem::GarageDoor;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<GarageDoorOpenOrCloseGarageResult^>^ GarageDoorServiceEventAdapter::OpenOrCloseGarageAsync(_In_ AllJoynMessageInfo^ info, _In_ bool interfaceMemberOpen)
{
    auto args = ref new GarageDoorOpenOrCloseGarageCalledEventArgs(info, interfaceMemberOpen);
    AllJoynHelpers::DispatchEvent([=]() {
        OpenOrCloseGarageCalled(this, args);
    });
    return GarageDoorOpenOrCloseGarageCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<GarageDoorOpenGarageResult^>^ GarageDoorServiceEventAdapter::OpenGarageAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorOpenGarageCalledEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        OpenGarageCalled(this, args);
    });
    return GarageDoorOpenGarageCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<GarageDoorCloseGarageResult^>^ GarageDoorServiceEventAdapter::CloseGarageAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorCloseGarageCalledEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        CloseGarageCalled(this, args);
    });
    return GarageDoorCloseGarageCalledEventArgs::GetResultAsync(args);
}

// Property Reads
IAsyncOperation<GarageDoorGetVersionResult^>^ GarageDoorServiceEventAdapter::GetVersionAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorGetVersionRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetVersionRequested(this, args);
    });
    return GarageDoorGetVersionRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<GarageDoorGetServiceVersionResult^>^ GarageDoorServiceEventAdapter::GetServiceVersionAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorGetServiceVersionRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetServiceVersionRequested(this, args);
    });
    return GarageDoorGetServiceVersionRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<GarageDoorGetLocationResult^>^ GarageDoorServiceEventAdapter::GetLocationAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorGetLocationRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetLocationRequested(this, args);
    });
    return GarageDoorGetLocationRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<GarageDoorGetDoorStateResult^>^ GarageDoorServiceEventAdapter::GetDoorStateAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new GarageDoorGetDoorStateRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetDoorStateRequested(this, args);
    });
    return GarageDoorGetDoorStateRequestedEventArgs::GetResultAsync(args);
}

// Property Writes
IAsyncOperation<GarageDoorSetLocationResult^>^ GarageDoorServiceEventAdapter::SetLocationAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ value)
{
    auto args = ref new GarageDoorSetLocationRequestedEventArgs(info, value);
    AllJoynHelpers::DispatchEvent([=]() {
        SetLocationRequested(this, args);
    });
    return GarageDoorSetLocationRequestedEventArgs::GetResultAsync(args);
}

