//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace net { namespace protosystem { namespace GarageDoor {

ref class GarageDoorConsumer;

public ref class GarageDoorOpenOrCloseGarageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static GarageDoorOpenOrCloseGarageResult^ CreateSuccessResult()
    {
        auto result = ref new GarageDoorOpenOrCloseGarageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static GarageDoorOpenOrCloseGarageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorOpenOrCloseGarageResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class GarageDoorOpenGarageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static GarageDoorOpenGarageResult^ CreateSuccessResult()
    {
        auto result = ref new GarageDoorOpenGarageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static GarageDoorOpenGarageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorOpenGarageResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class GarageDoorCloseGarageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static GarageDoorCloseGarageResult^ CreateSuccessResult()
    {
        auto result = ref new GarageDoorCloseGarageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static GarageDoorCloseGarageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorCloseGarageResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class GarageDoorJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property GarageDoorConsumer^ Consumer
    {
        GarageDoorConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ GarageDoorConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    GarageDoorConsumer^ m_consumer;
};

public ref class GarageDoorGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static GarageDoorGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new GarageDoorGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        return result;
    }

    static GarageDoorGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorGetVersionResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint16 m_value;
};

public ref class GarageDoorGetServiceVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 ServiceVersion
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static GarageDoorGetServiceVersionResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new GarageDoorGetServiceVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ServiceVersion = value;
        return result;
    }

    static GarageDoorGetServiceVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorGetServiceVersionResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint32 m_value;
};

public ref class GarageDoorGetLocationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ Location
    {
        Platform::String^ get() { return m_value; }
    internal:
        void set(_In_ Platform::String^ value) { m_value = value; }
    }

    static GarageDoorGetLocationResult^ CreateSuccessResult(_In_ Platform::String^ value)
    {
        auto result = ref new GarageDoorGetLocationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Location = value;
        return result;
    }

    static GarageDoorGetLocationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorGetLocationResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    Platform::String^ m_value;
};

public ref class GarageDoorSetLocationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static GarageDoorSetLocationResult^ CreateSuccessResult()
    {
        auto result = ref new GarageDoorSetLocationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static GarageDoorSetLocationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorSetLocationResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class GarageDoorGetDoorStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property GarageDoorDoorState^ DoorState
    {
        GarageDoorDoorState^ get() { return m_value; }
    internal:
        void set(_In_ GarageDoorDoorState^ value) { m_value = value; }
    }

    static GarageDoorGetDoorStateResult^ CreateSuccessResult(_In_ GarageDoorDoorState^ value)
    {
        auto result = ref new GarageDoorGetDoorStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->DoorState = value;
        return result;
    }

    static GarageDoorGetDoorStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new GarageDoorGetDoorStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    GarageDoorDoorState^ m_value;
};

} } } 
