//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace net { namespace protosystem { namespace GarageDoor {

public interface class IGarageDoorService
{
public:
    // Implement this function to handle calls to the OpenOrCloseGarage method.
    Windows::Foundation::IAsyncOperation<GarageDoorOpenOrCloseGarageResult^>^ OpenOrCloseGarageAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ bool interfaceMemberOpen);

    // Implement this function to handle calls to the OpenGarage method.
    Windows::Foundation::IAsyncOperation<GarageDoorOpenGarageResult^>^ OpenGarageAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the CloseGarage method.
    Windows::Foundation::IAsyncOperation<GarageDoorCloseGarageResult^>^ CloseGarageAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle requests for the value of the Version property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<GarageDoorGetVersionResult^>^ GetVersionAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the ServiceVersion property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<GarageDoorGetServiceVersionResult^>^ GetServiceVersionAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Location property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<GarageDoorGetLocationResult^>^ GetLocationAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the Location property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<GarageDoorSetLocationResult^>^ SetLocationAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, Platform::String^ value);

    // Implement this function to handle requests for the value of the DoorState property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<GarageDoorGetDoorStateResult^>^ GetDoorStateAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } 
