//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace net { namespace protosystem { namespace SmartSpaces { namespace Environment { namespace CurrentTemperature {

ref class CurrentTemperatureConsumer;

public ref class CurrentTemperatureSetLocationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static CurrentTemperatureSetLocationResult^ CreateSuccessResult()
    {
        auto result = ref new CurrentTemperatureSetLocationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static CurrentTemperatureSetLocationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new CurrentTemperatureSetLocationResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class CurrentTemperatureJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property CurrentTemperatureConsumer^ Consumer
    {
        CurrentTemperatureConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ CurrentTemperatureConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    CurrentTemperatureConsumer^ m_consumer;
};

public ref class CurrentTemperatureGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static CurrentTemperatureGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new CurrentTemperatureGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        return result;
    }

    static CurrentTemperatureGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new CurrentTemperatureGetVersionResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint16 m_value;
};

public ref class CurrentTemperatureGetCurrentValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double CurrentValue
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static CurrentTemperatureGetCurrentValueResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new CurrentTemperatureGetCurrentValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->CurrentValue = value;
        return result;
    }

    static CurrentTemperatureGetCurrentValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new CurrentTemperatureGetCurrentValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    double m_value;
};

public ref class CurrentTemperatureGetLocationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ Location
    {
        Platform::String^ get() { return m_value; }
    internal:
        void set(_In_ Platform::String^ value) { m_value = value; }
    }

    static CurrentTemperatureGetLocationResult^ CreateSuccessResult(_In_ Platform::String^ value)
    {
        auto result = ref new CurrentTemperatureGetLocationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Location = value;
        return result;
    }

    static CurrentTemperatureGetLocationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new CurrentTemperatureGetLocationResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    Platform::String^ m_value;
};

} } } } } 
